name: Variable
on: 
  workflow_dispatch:
env:
  MY_VARIABLE: ${{ secrets.MY_SECRET}}
jobs:
  print-variable:
    runs-on: ubuntu-latest
    steps:
      - name: Print Variable
        run: echo "secret:" $MY_VARIABLE